name:                term-rewriter
version:             0.1.0.0
github:              "oyeb/term-rewriter"
license:             BSD3
author:              "Ananya Bahadur"
maintainer:          "ananya95@gmail.com"
copyright:           "2020 Ananya Bahadur"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/oyeb/term-rewriter#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  term-rewriter-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - term-rewriter

tests:
  term-rewriter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - term-rewriter
    - hspec
